version: '3.3'

services:
    web-desktop:
        build: 
            context: .
            dockerfile: dockerfile.webdesktop        
        ports:
            - 6901:6901
            - 5901:5901



            

