version: '3.3'

services:
    web-desktop:
        build: 
            context: .
            dockerfile: dockerfile.webtop  
        shm_size: 1GB          
        ports:
            - 3000:3000
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - SUBFOLDER=/
            - KEYBOARD=fr-fr-azerty
        volumes:
            - ./config:/config
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        security_opt:
            - seccomp:unconfined    

            

